### PR TITLE
Add tabs & contracts

### PR DESCRIPTION
**Pull request by pi0neerpat**
## Tabs

Tabs can be managed in /src/dashboard/helpers/general.js

## Context

Currently, if the ethers.js fails to load, context is never intialized with the user's wallet address, etc.

We can set a default context, however I think we should build without requiring context to load properly. e.g., app works even when context is undefined.

## Contracts

I imported the rToken contracts from the repo. Now, if you want to update the contracts that ethers.js will use:

1. cd rToken-contracts & git pull
2. `npm update-contracts` in the root directory 

## Other

- Added favicon
- Added Material-ui. Will need to change theme (using ThemeProvider?)

### CODE REVIEW

**Comment by pi0neerpat** [comment]
image

**Comment by ejwessel** [comment]
We should also limit the areas where context is used. If its displaying data then it should import the usage of context. I think there were a few general places where I saw it being used and it didn't need to be used.

**Comment by pi0neerpat** [comment]
> > I imported the rToken contracts from the repo.
> 
> Use a git submodule or see if they have turned it into a package that can be imported.

I am going to skip this for now, since I've made a card for it in Trello.

**Comment by pi0neerpat** [comment]
> We should also limit the areas where context is used. If its displaying data then it should import the usage of context. I think there were a few general places where I saw it being used and it didn't need to be used.

Once we get ESLint set up, this will identify all the unused variables. I'm not going to hunt for them manually.

**Comment by brianwchou** [comment]
I changed the fetching address for the DAI abi from `0xbF7A7169562078c96f0eC1A8aFD6aE50f12e5A99` 
to
`0xC4375B7De8af5a38a93548eb8453a498222C4fF2`

**Pull request merged**
